---
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/concourse:utt']
    id: 'utt'
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/concourse:utt'
      - '-f'
      - 'Dockerfile-utt'
      - '.'
    waitFor: ['utt']

images:
  - 'gcr.io/$PROJECT_ID/concourse:utt'
